"project_id": "705247"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    "source": "Den/InfoPlist.xcstrings",
    "translation": "Den/InfoPlist.xcstrings",
    "multilingual": true
  },
  {
    "source": "Shared/Localizable.xcstrings",
    "translation": "Shared/Localizable.xcstrings",
    "multilingual": true
  },
  {
    "source": "WidgetExtension/InfoPlist.xcstrings",
    "translation": "WidgetExtension/InfoPlist.xcstrings",
    "multilingual": true
  },
]
