"project_id": "705247"
"base_path": "."
"base_url": "https://api.crowdin.com"

#
# Files configuration
#
files: [
  {
    #
    # Source files filter
    # e.g. "/resources/en/*.json"
    #
    "source": "Den/InfoPlist.xcstrings",

    #
    # Where translations will be placed
    # e.g. "/resources/%two_letters_code%/%original_file_name%"
    #
    "translation": "Den/InfoPlist.xcstrings"
  },
  {
    "source": "Den/Localizable.xcstrings",
    "translation": "Den/Localizable.xcstrings"
  }
]
