# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :mac do
  lane :screenshots do
    capture_screenshots(scheme: "Screenshots")
  end
end

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "Screenshots")
  end
  lane :beta do
    get_certificates(
      platform: "ios"
    )
    build_app(
      scheme: "Den",
      export_method: "app-store",
      output_directory: "fastlane/beta/ios",
      sdk: "iphoneos",
      xcargs: "-allowProvisioningUpdates"
    )
  end
end
